function on_mcm_load()
    options = {
        id = "talker",
        sh = true,
        gr = {
            -- Model Choice
            { id = "gpt_version", type = "radio_h", val = 2, def = 2, content = {
                {1, "gpt-4o-mini"},
                {2, "gpt-4o"},
                {3, "gpt-4-turbo"}
                }
            },
            {id = "speak_key_title", type = "desc", clr = {200, 200, 255, 200}, text="ui_mcm_talker_speak_key_title"},
            {id = "speak_key_description", type = "desc", text="ui_mcm_talker_speak_key_description"},
            {id = "speak_key", type = "key_bind", val = 2, def = DIK_keys.DIK_LMENU},
        }
    }
    return options
end

-- Default configuration values
local defaults = {
	["speak_key"] = DIK_keys.DIK_LMENU,
    ["gpt_version"] = 2, -- as def=1 is set in options
}

-- Function to retrieve the configuration value
function get(key)
    if ui_mcm then
        return ui_mcm.get("talker/" .. key)
    else
        return defaults[key]
    end
end